# Generated by Django 4.2.4 on 2023-09-02 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='private_key',
            field=models.TextField(blank=True, null=True, verbose_name='Chave privada'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='public_key',
            field=models.TextField(blank=True, null=True, verbose_name='Chave pública'),
        ),
    ]
