# Generated by Django 4.2.4 on 2023-09-02 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_private_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='private_key',
            field=models.BinaryField(blank=True, null=True, verbose_name='Chave privada'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='public_key',
            field=models.BinaryField(blank=True, null=True, verbose_name='Chave pública'),
        ),
    ]
