# Generated by Django 4.2.4 on 2023-09-02 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='signed_hash',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Hash Assinado'),
        ),
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.TextField(verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='document',
            name='signature',
            field=models.TextField(blank=True, null=True, verbose_name='Assinatura'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
    ]
