# Generated by Django 4.2.4 on 2023-09-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_signed_hash_alter_document_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='signed_hash',
        ),
        migrations.AlterField(
            model_name='document',
            name='signature',
            field=models.BinaryField(blank=True, null=True, verbose_name='Assinatura'),
        ),
    ]
